--- #YAML:1.0
name: CGI-Application-Dispatch
version: 1.01
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: Class used to dispatch request to CGI::Application based objects
license: perl
generated_by: Module::Build version 0.2604, without YAML.pm
