---
name: CGI-Application-Dispatch
version: 2.10
author:
  - 'Michael Peters <mpeters@plusthree.com>'
abstract: Dispatch requests to CGI::Application based objects
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI::Application: 3.2
  Exception::Class: 0
  Exception::Class::TryCatch: 0
  Test::More: 0
  perl: 5.6.0
build_requires:
  Test::LongString: 0
provides:
  CGI::Application::Dispatch:
    file: lib/CGI/Application/Dispatch.pm
    version: 2.10
  CGI::Application::Dispatch::Regexp:
    file: lib/CGI/Application/Dispatch/Regexp.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
