--- #YAML:1.0
name: CGI-Application-Dispatch
version: 2.13_01
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: Dispatch requests to CGI::Application based objects
license: perl
generated_by: Module::Build version 0.261, without YAML.pm
