--- #YAML:1.0
name: CGI-Application-Dispatch
version: 0.02
author:
  - Michael Peters <michael@petersfamily.org>
abstract: |-
  Class used to dispatch request to CGI::Application based objects
license: perl
requires:
  CGI::Application: 3.2
  perl: 5.6.1
build_requires:
  Apache::FakeRequest: 0
provides:
  CGI::Application::Dispatch:
    file: lib/CGI/Application/Dispatch.pm
    version: 0.02
generated_by: Module::Build version 0.25
