---
abstract: 'Dispatch requests to CGI::Application based objects'
author:
  - 'Michael Peters <mpeters@plusthree.com>'
build_requires:
  Test::LongString: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Dispatch
provides:
  CGI::Application::Dispatch:
    file: lib/CGI/Application/Dispatch.pm
    version: 2.18
  CGI::Application::Dispatch::Regexp:
    file: lib/CGI/Application/Dispatch/Regexp.pm
    version: 2.13
requires:
  CGI::Application: 3.2
  Exception::Class: 0
  Exception::Class::TryCatch: 0
  perl: v5.6.0
  version: 0.82
resources:
  license: http://dev.perl.org/licenses/
version: 2.18
