--- #YAML:1.0
name: CGI-Application-Dispatch
version: 2.00_05
author:
  - Michael Peters <mpeters@plusthree.com>
abstract: Dispatch requests to CGI::Application based objects
license: perl
generated_by: Module::Build version 0.2612, without YAML.pm
