---
abstract: 'Dispatch requests to CGI::Application based objects'
author:
  - 'Michael Peters <mpeters@plusthree.com>'
build_requires:
  CGI::PSGI: 0
  Plack: 0.9956
  Test::LongString: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Dispatch
provides:
  CGI::Application::Dispatch:
    file: lib/CGI/Application/Dispatch.pm
    version: 3.10
  CGI::Application::Dispatch::PSGI:
    file: lib/CGI/Application/Dispatch/PSGI.pm
    version: 3.10
  CGI::Application::Dispatch::Regexp:
    file: lib/CGI/Application/Dispatch/Regexp.pm
    version: 3.04
requires:
  CGI::Application: 4.50
  Exception::Class: 1.2
  HTTP::Exception: 0
  Try::Tiny: 0
  perl: v5.6.0
  version: 0.82
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/markstos/CGI--Application--Dispatch
version: 3.10
